// Education: B.Tech in Computer Science
// Years of Experience: 3.5 years ( full time )
// Date of the Interview: Dec '23
// Prior Experience: Product Based Company
// Location: Flexible - Remote / Bengaluru, India
// Applied on Instahyre, got call from recruiter. Interviews were scheduled ~1 month post initial discussion.

// Round 1: JavaScript + Web (Expected duration: 60mins, Actual duration: 90mins in my case)

// Introductions (5mins)
// 3-4 Js Output based questions (complex questions mostly around "this" context, call, apply, arrow fns)
// Currying problem (slight variation, don't recall exactly)
// Array.reduce polyfill and follow up problem statement on the same.
// write a fn to call api and abort after certain time interval. (similar to implementing autosuggest)
// Post interview discussions (10mins)
// Round 2: UI Tech / Machine Coding (Duration: 60mins)

// Implement inheritance in JavaScript (prototype chain) and questions around the same.
// Machine coding- Similar to building a login form (free to choose any framework)
// Round 3: Hiring Manager (Expected duration: 60mins, Actual duration: 90mins in my case)

// Introductions.
// Resume / Project related discussions.
// Discussions around SDLC, observability, debuggability, performance etc.
// Follow up questions on specific scenarios.
// General behavioural / cultural discussions.
// Offer: https://leetcode.com/discuss/compensation/4751520/Angel-One-or-SDE-2-Frontend-or-Remote-Bangalore-India-or-Accepted/