
// India
// Interview
// Education: BE (ECE) from Tier-3 College
// Status: 2.7 years of experience at 2 product based companies
// Source: https://leetcode.com/discuss/study-guide/4788101/Frontend-PSDS-Round : Practice this for the Problem Solving Round

// Rounds:
// 3 Techinal Rounds
// 1 AVP Round
// 1 SVP Round
// 1 HR Round

// Techinal Round 1 - (Problem Solving Round):
// 3 problem were given to me, in which I have to solve 2 problems.
// 1st Problem : Find the cycle in nested Object
// 2nd Problem: pollyfill for setInterval and clearInterval
// 3rd Problem: pollyfill for Promise.all with some conditions i.e. at a time n number of promises should be resolved if any of them is resolved then take n+1 promise in a stack

// Verdict: I was able to solve all the problems, interviewrs were very much helful, I stucked in the 3rd problem but with the help of them, I was able to solve.

// Techinal Round 2 - (Web Fundamental Round):
// Questions based on Currying, CORS, preflight request, web performance, etc...

// Verdict: Selected

// Techinal Round 3 - (System Design Round):
// Discussed about the system design of the Google docs. This includes the data management on the frontend side, how can I send the data, how can I edit, add colors etc. All the things discussed on aspect of Frontend Only.

// Vedict: Selected

// AVP Round:
// Normal discussion with the AVP about the company and normal techinal questions regarding sockets( because it was present in the Resume )

// Verdict: Selected

// SVP Round:
// General discussion about me and past projects

// Verdict: Selected

// HR Round:
// More focused on my approch to handle things. More on a behavioural round.

// Vedict: Selected

// Offer discussion is going on, add it once I get.

// Feel free to ask questions if you have any.