// First Round:
// This round is mainly on data structure and Algorithms. The questions will be like the medium-level questions in the LeetCode. They will be looking for the method of solving not exactly a solution, but try to finish the question with the best solutions. In the end, there were simple questions on HTML, CSS, and Javascript.

// Second Round:
// In this Round, you will be asked questions on HTML, CSS, Javascript, and ReactJS, most of these are based on therotical try to answer by giving examples.
// After these, you should build a UI application on ReactJS. Try to build the application with considering optimization and browser performance.
// In the end, you will be asked questions on the optimization and performance of web applications.

// Manager Round:
// This round contains most of the questions on leadership principles and simple technical questions.

// Finally, I couldn't accept the offer as I got a better offer.