// TOE 2.5+

// Round 1: (taken by third party)
// currying coding question
// flatten array question
// What is call, bind, apply ?
// What is Event loop ?
// Discussion on projects
// How would you design searchbar with matching words ?
// How would you do performance optimization ?
// given an api, fetch data and render it in table (React js)
// Round 2:
// How would you render millions of data on UI using react ?
// discussion on promise
// polyfill for promise
// Round 3 (Taken by manager)
// Projects discussion
// code mapLimit function for limiting async calls using callback
// Implement caching in that.
// Compensation details: https://leetcode.com/discuss/compensation/4803797/Quince-or-SDE2-or-Frontend-or-Bangalore-or-Rejecting
// (Hope it helps!)

// 30 min recruiter call. After that, received a Hackerrank live coding link via mail.
// First technical round:
// 5 min - Introductions
// 25 mins - Implement JS throttling function
// 25 mins - Implement fetch call and display data from an external API on a react app. Follow-up questions on todo.
// 5 min - Info on how next rounds going to be. (Expecting DSA, Frontend System Design, Behavioural questions)
// For next technical round, received a mail saying they found a better candidate.